FIND_PATH(SILO_INCLUDE_DIRS
		NAMES silo.inc
		HINTS ${SILO_ROOT} /usr/local
		PATH_SUFFIXES include 
		DOC "PATH TO silo.inc")

FIND_LIBRARY(SILO_LIBRARIES
		NAMES siloh5
		HINTS ${SILO_ROOT} /usr/local
		PATH_SUFFIXES lib 
		DOC "PATH TO libsilo.a or libsiloh5.a")

IF (SILO_INCLUDE_DIRS AND SILO_LIBRARIES)
   SET(SILO_FOUND YES)
   MESSAGE(STATUS "SILO FOUND")
ENDIF(SILO_INCLUDE_DIRS AND SILO_LIBRARIES)
