# SCons file for the unit test of the QN solver
import os
import socket
import distutils. util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'hostname: ' + hostname
print 'platform: ' + platform

env = Environment(F90PATH = ['../memory','../precision'],
                  FORTRANMODDIRPREFIX = '-J',
                  LIBPATH = ['.'],
                  LIBS = ['sll_memory','sll_precision','lapack','dfftpack'],
                  F90FLAGS = ['-g','-O2','-W','-Wall','-Werror','-fall-intrinsics','-std=f95','-DDEBUG','-ffree-line-length-none'])
# The -fall-intrinsics flag is used to permit the use of the etime intrinsic, which is a GNU extension and not part of the F95 standard.

env.Library('sll_memory',["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Program('unit_test', ["unit_test.F90", "bsplvb.F90", "bsplvd.F90","sll_quasi_neutral_solver.F90"])
