#!/bin/bash
 
# Every night, each entry following '#PIPOL' is passed as argument to
# a pipol-sub command:

# There is two ways to make a reservation via pipol-sub:
# --> Add a line per image with the following syntaxe:
# '#PIPOL esn amd64-linux-debian-testing.dd none 2:00 --silent --user'
#  (1)    (2) (3)                           (4)  (5)  (6)      (7)
     
# (1) comment token known by pipol
# (2) a reservation as soon as possible (at night, reservations are starting at 20h30)
# (3) the system image
# (4) none as we do not want a particular host
# (5) the reservation is for two hours
# (6) do not send reservation emails
# (7) run as user (You can only run the script as root for the Windows Images).

# Use entries only if you need them!

# --> The second way is to use pipol-sub shortcut:
# '#PIPOL debian 2:00 --root`
#  (1)         (2)       (3)    (4)

# (1)  Comment token known by pipol
# (2)  The string to matched with. 
#	   In this example the line will reserve and deploy all the Debian images.
#        For example, the line: #PIPOL linux 2:00 --root will reserve and deploy all the linux images.
#        For more informations, please read the documentation: http://pipol.inrialpes.fr/documentation/manual/user-manual/user-manual.html#ex-cutions-en-batch-mode-simplifi
# (3)  The reservation is for two hours
# (4)  Some options, please read the documentation for more details

#PIPOL amd64_2010-linux-debian-testing 1:00 
#PIPOL amd64_2010-linux-debian-squeeze 1:00 
#PIPOL amd64_2010-linux-fedora-core16 1:00
#PIPOL amd64-linux-fedora-core15 1:00
#PIPOL amd64-linux-fedora-core16 1:00
#PIPOL amd64-linux-ubuntu-natty 1:00
#PIPOL amd64-linux-ubuntu-oneiric 1:00
#PIPOL amd64-linux-ubuntu-precise 1:00
#PIPOL x86_64_mac-mac-osx-server-snow-leopard 2:00

HOST=`hostname -s`
echo "${HOST}"
ARCH=`uname -s`

if [[ $PIPOL_IMAGE_NAME ]]; then
   echo "PIPOL_IMAGE_NAME:${PIPOL_IMAGE_NAME}"
else
   echo "ARCH:${ARCH}"
fi

if [[ $PIPOL_WDIR ]] ; then
   echo "PIPOL_WDIR:$PIPOL_WDIR"
   WORKDIR=$PIPOL_WDIR
elif [[ "$HOST" == *-navaro* ]]; then
   WORKDIR="/tmp"
elif [[ "$HOST" == *-doct-* ]]; then
   WORKDIR="/Users/irma"
elif [[ "$HOST" == *irma-* ]]; then
   WORKDIR="/scratch/navaro"
else
   WORKDIR="./"
fi

echo "WORDIR:$WORKDIR"
cd $WORKDIR

if [[ $PIPOL_HOMEDIR ]] ; then
   echo "PIPOL_HOMEDIR:$PIPOL_HOMEDIR"
   echo "PIPOL_IMAGE_NAME:${PIPOL_IMAGE_NAME}"
   HOMEDIR=$PIPOL_HOMEDIR
elif [[ "$HOST" == *-navaro* ]] ; then
   HOMEDIR="${HOME}/Codes"
elif [[ "$HOST" == *-doct-* ]]; then
   HOMEDIR="/Users/irma"
elif [[ "$HOST" == *irma-* ]]; then
   HOMEDIR=${HOME}/Vlasov
else
   echo "wtf?"
fi

echo "HOMEDIR:${HOMEDIR}"

cd ${HOMEDIR}/selalib; {
   git fetch origin
   git checkout phdf5-3d
   git merge origin/phdf5-3d
   git log --date-order --date=short | \
   sed -e '/^commit.*$/d' | \
   awk '/^Author/ {sub(/\\$/,""); getline t; print $0 t; next}; 1' | \
   sed -e 's/^Author: //g' | \
   sed -e 's/>Date:   \([0-9]*-[0-9]*-[0-9]*\)/>\t\1/g' | \
   sed -e 's/^\(.*\) \(\)\t\(.*\)/\3    \1    \2/g' > ChangeLog
}; cd -

if [[ $PIPOL_IMAGE_NAME == *-fedora-* ]]; then
   echo "Fedora core"
   module load openmpi-x86_64
fi

if [ "$PIPOL_IMAGE_NAME" = "x86_64_mac-mac-osx-server-snow-leopard" ]; then
   echo "Configuration pour MACOS SNOWLEOPARD"
   export PATH=/usr/local/bin:${PATH}
   export CC=/usr/local/bin/gcc
   export CXX=/usr/local/bin/g++
   export FC=/usr/local/bin/gfortran
   export OMPI_FC=/usr/local/bin/gfortran
   export OMPI_CC=/usr/local/bin/gcc
   export HDF5_ROOT=/usr/local
   export FFTW_ROOT=/usr/local
fi

mkdir build
cd build; { 
    ## 2.1) configuration
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local ${HOMEDIR}/selalib
    make NightlyUpdate
    make NightlyConfigure

    ## 2.2) build
    make NightlyBuild

    ## 2.3) test
    make NightlyTest

    ## 2.4) submission on a dashboard
    make NightlySubmit

    ## 2.4) packaging: PIPOL_CPACK_G and PIPOL_PACK_EXT are set by PIPOL
    cpack -G $PIPOL_CPACK_G .
}; cd -

# 3) with cmake test results can be seen on 
# http://cdash.inria.fr/CDash/index.php?project=Pipol

exit 0

