FIND_LIBRARY(FFTPACK_LIBRARIES
		NAMES dfftpack
		HINTS /usr/local
		PATH_SUFFIXES lib 
		DOC "PATH TO libdfftpack")

IF (FFTPACK_LIBRARIES)

   MESSAGE(STATUS "FFTPACK FOUND")

ELSE()

   MESSAGE(STATUS "FFTPACK NOT FOUND ... BUILD SOURCE")
   ADD_SUBDIRECTORY(${PROJECT_SOURCE_DIR}/../fftpack ${PROJECT_BINARY_DIR}/dfftpack)
   SET(FFTPACK_LIBRARIES dfftpack)

ENDIF(FFTPACK_LIBRARIES)

SET(FFTPACK_FOUND YES)
