# SCons file to build the test case for the memory allocator
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment(F90 = 'gfortran',
                  ENV = os.environ,
                  LIBPATH = ['.'], 
                  F90FLAGS = ['-g', '-W', '-Wall', '-Werror', '-std=f95', '-DDEBUG', '-DGFORTRAN', '-ffree-line-length-none'] )
src_files = Split('tester.F90 sll_memory.F90')
env.Library('sll_memory','sll_memory.F90')
env.Program(target='unit_test', source = src_files)
