# SCons file to build the test case for the memory allocator
import os
env = Environment(CC = 'gfortran', CPPFLAGS = '-ffree-line-length-none', 
                  CCFLAGS = '-W -Wall -std=f95')
src_files = Split('tester.F90 sll_memory.F90')
env.Program(target='unit_test', source = src_files)
