# SCons file to build the test case for the memory allocator
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment( ENV = os.environ,
                   LIBPATH = ['.'], 
                   F90FLAGS = ['-g', '-W', '-Wall', '-Werror', '-std=f2003', 
                               '-DDEBUG', '-DGFORTRAN', 
                               '-ffree-line-length-none'] )
src_files = Split('unit_test.F90 sll_memory.F90')
env.Program(target='unit_test', source = src_files)
