# SCons file for the unit test of the cylindrical mesh type
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform


if os.environ.has_key("HDF5INCPATH"):
   print 'hdf5 header files are in %s ' %  os.environ['HDF5INCPATH']
else:
   os.environ['HDF5INCPATH'] = "/usr/local/include"

if os.environ.has_key("HDF5MODPATH"):
   print 'hdf5 mod files are in %s ' %  os.environ['HDF5MODPATH']
else:
   os.environ['HDF5MODPATH'] = "/usr/local/include"

if os.environ.has_key("HDF5LIBPATH"):
   print 'hdf5 library files are in %s ' %  os.environ['HDF5LIBPATH']
else:
   os.environ['HDF5LIBPATH'] = "/usr/local/lib"

vars = Variables()
vars.Add('HDF5INCPATH', 'hdf5 header files location',os.environ['HDF5INCPATH'])
vars.Add('HDF5MODPATH', 'fortran module hdf5.mod location',os.environ['HDF5MODPATH'])
vars.Add('HDF5LIBPATH', 'hdf5 library location',os.environ['HDF5LIBPATH'])

env = Environment( ENV = os.environ, 
                   variable = vars,
                   F90FLAGS = ['-g', '-W', '-Wall', 
                               '-ffree-line-length-none',
                               '-fbounds-check'],
                   F90PATH = ['../memory',
                              '../precision',
                              '../assert',
                              '../utilities',
                              '../constants',
                              '../mesh_types',
                              '../splines',
                              '../ode_solvers'],
                   LIBPATH = ['.'],
                   LIBS = ['sll_memory',
                           'sll_precision',
                           'sll_assert',
                           'sll_utilities',
                           'sll_constants',
                           'sll_mesh_types',
                           'sll_splines',
                           'sll_ode_solvers',
                           'sll_distribution_function',
                           'sll_diagnostics',
                           'sll_poisson_solvers'])

env.Append(CPPDEFINES=['NOHDF5','DEBUG','GFORTRAN'])

env.Append(LIBS=['dfftpack'])

#env.Append(F90PATH=['${HDF5INCPATH}','${HDF5MODPATH}'])
#env.Append(LIBPATH= ['${HDF5LIBPATH}'])

env.Library('sll_memory',["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Library('sll_assert', ["../assert/sll_assert.F90"])
env.Library('sll_ode_solvers',["../ode_solvers/sll_ode_solvers.F90"])
env.Library('sll_splines', ["../splines/sll_splines.F90"])
env.Library('sll_constants', ["../constants/numeric_constants.F90"])
env.Library('sll_utilities',["../utilities/misc_utils.F90"])
env.Library('sll_diagnostics',Glob("../diagnostics/sll_*.F90"))
env.Library('sll_mesh_types', ["../mesh_types/sll_mesh_types.F90","../mesh_types/geometry_functions.F90"])
env.Library('sll_distribution_function', ["../distribution_function/sll_distribution_function.F90"])
env.Library('sll_poisson_solvers', ["../poisson_solvers/sll_poisson_2D_periodic.F90",
                                    "../poisson_solvers/fft_module.F90"])

env.Program('unit_test', ["unit_test.F90", "sll_bsl.F90"])
env.Program('landau_dumping', ["landau_dumping.F90", "sll_bsl.F90"])

Help(vars.GenerateHelpText(env))
