# SCons file for the unit test of the cylindrical mesh type
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform

vars = Variables()
vars.Add('HDF5INCPATH','HDF5 header files location','/usr/local/include')
vars.Add('HDF5LIBPATH','HDF5 libraries location','/usr/local/lib')
vars.Add('HDF5MODPATH','HDF5 fortran module location','/usr/local/include')

env = Environment( ENV = os.environ, variable = vars,
                   F90FLAGS = ['-g', '-W', '-Wall', '-std=f2003', '-DDEBUG',
                               '-DGFORTRAN','-ffree-line-length-none',
                               '-fbounds-check'],
                   F90PATH = ['../memory','../precision','../assert',
                              '../utilities','../constants','../mesh_types',
                              '../splines','../ode_solvers', '/usr/local/include'
                              '${HDF5INCPATH}','${HDF5MODPATH}'],
                   LIBPATH= ['.', '${HDF5LIBPATH}'],
                   LIBS=['sll_memory','sll_precision','sll_assert',
                         'sll_utilities', 'sll_constants','sll_mesh_types',
                         'sll_splines','sll_ode_solvers',
                         'sll_distribution_function','sll_diagnostics',
                         'hdf5_fortran','hdf5','z'])

env.Library('sll_memory',["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Library('sll_assert', ["../assert/sll_assert.F90"])
env.Library('sll_ode_solvers',["../ode_solvers/sll_ode_solvers.F90"])
env.Library('sll_splines', ["../splines/sll_splines.F90"])
env.Library('sll_constants', ["../constants/numeric_constants.F90"])
env.Library('sll_utilities',["../utilities/misc_utils.F90"])
env.Library('sll_diagnostics',Glob("../diagnostics/sll_*.F90"))
env.Library('sll_mesh_types', ["../mesh_types/sll_mesh_types.F90","../mesh_types/geometry_functions.F90"])
env.Library('sll_distribution_function', ["../distribution_function/sll_distribution_function.F90"])
env.Program('unit_test', ["unit_test.F90", "sll_bsl.F90"])

Help(vars.GenerateHelpText(env))
