# SCons file for the unit test of the tridiagonal setter/solver
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment( ENV = os.environ,
                   F90PATH = ['../memory','../precision'],
                   FORTRANMODDIRPREFIX= '-J', 
                   LIBPATH= ['.'],
                   LIBS=['sll_memory','sll_precision'],
                   F90FLAGS = ['-g', '-W', '-Wall', '-std=f2003', 
                               '-DDEBUG','-ffree-line-length-none'])
                   #I've deleted the '-Werror' flag. De Santis S.
#env.Replace(	
#		F90FLAGS = OPT+' -fpp',
#		FORTRANMODDIR = ZZZZZZ
#env.Append(LIBS = ['nsl', 'socket'])

env.Library('sll_memory',    ["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Program('unit_test',     ["unit_test.F90", "tridiagonal.F90"])
env.Program('example',     ["example.F90", "tridiagonal.F90"])



