# Get the RedHat/CentOS version
if(EXISTS "/etc/redhat-release")
   file(READ "/etc/redhat-release" _REDHAT_RELEASE_CONTENT)
   string(REGEX REPLACE "[^0-9.]*([0-9.]+)[^0-9.]*\$" "\\1" ${RH_VERSION}
           "${_REDHAT_RELEASE_CONTENT}"
        )
   set(LINUX_NAME ${RH_VERSION})
endif()

FIND_PROGRAM(LSB_RELEASE_COMMAND NAMES lsb_release)
if(LSB_RELEASE_COMMAND)
   EXECUTE_PROCESS(
      COMMAND ${LSB_RELEASE_COMMAND} -is
      COMMAND tr -d '\n'
      OUTPUT_VARIABLE LSB_ID
   )
   EXECUTE_PROCESS(
      COMMAND ${LSB_RELEASE_COMMAND} -rs
      COMMAND tr -d '\n'
      OUTPUT_VARIABLE LSB_VER
   )

   set(LINUX_NAME "${LSB_ID}-${LSB_VER}")

endif()


MESSAGE(STATUS "LINUX_NAME:${LINUX_NAME}")

SET(CTEST_PROJECT_NAME "Selalib")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE_CDASH TRUE)
SET(CTEST_DROP_SITE "cdash.inria.fr")
SET(CTEST_DROP_LOCATION "/CDash/submit.php?project=Selalib")
SET(CTEST_TRIGGER_SITE "")
FIND_PROGRAM(CTEST_GIT_COMMAND NAMES git)
SET(UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

IF(LINUX_NAME)
SET(BUILDNAME "${Fortran_COMPILER_NAME}-${Fortran_COMPILER_VERSION}-${LINUX_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
ELSE()
SET(BUILDNAME "${Fortran_COMPILER_NAME}-${Fortran_COMPILER_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
ENDIF()
MESSAGE(STATUS "BUILDNAME:${BUILDNAME}")
