# SCons file for the unit test of the assertion module
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment( ENV = os.environ,
                   F90PATH = ['../memory','../precision'],
                   FORTRANMODDIRPREFIX= '-J', 
                   LIBPATH= ['.'],
                   LIBS=['sll_memory','sll_precision'],
                   F90FLAGS = ['-g', '-W', '-Wall', '-Werror', '-std=f2003','-DDEBUG','-DGFORTRAN','-ffree-line-length-none'])

env.Library('sll_memory',["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Program('unit_test', ["unit_test.F90", "sll_assert.F90"])



