# SCons file for the unit test of the diagnostics
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment( ENV = os.environ,
                   F90FLAGS =['-g', '-W', '-Wall', '-Wextra', '-pedantic', 
                              '-std=f2003', '-ffree-line-length-none'],
                   CPPDEFINES=['GFORTRAN', 'DEBUG'],
                   F90PATH=['../precision','../assert',
                            os.environ['HDF5INCLUDEPATH']],
                   LIBPATH=['.',os.environ['HDF5LIBPATH']],
                   LIBS=[ 'sll_assertion', 'sll_precision', 'hdf5_fortran', 
                          'hdf5','z'])

env.Library('sll_precision',  ["../precision/sll_working_precision.F90"])
env.Library('sll_assertion',  ["../assert/sll_assert.F90"])
env.Program('unit_test', ["unit_test.F90","sll_diagnostics.F90","write_xdmf_xml.c"])

