# SCons file to build the test case for the memory allocator
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment(F90 = 'gfortran',
                  F90PATH= ['../memory','../precision','../assert', '../numerical_utilities','../constants'],
                  ENV = os.environ,
                  LIBPATH = ['.','../fftpack'],
                  LIBS = ['dfftpack','sll_memory','sll_precision','sll_assertion','sll_constants'],
                  F90FLAGS = ['-g', '-W', '-Wall', '-std=f2003', '-ffree-line-length-none','-fbounds-check'],
                  CPPDEFINES=['DEBUG','GFORTRAN'] )
   
src_files = ['fftpack.f90', 'dfftpack.f']
env.Library('dfftpack', src_files)
