# SCons file for the unit test of the spline module
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'hostname : ' + hostname
print 'platform : ' + platform
# WATCH OUT FOR THAT GFORTRAN VARIABLE
env = Environment(F90PATH = ['../memory','../precision','../assert', '../numerical_utilities','../constants'],
                  FORTRANMODDIRPREFIX= '-J', 
                  LIBPATH= ['.'],
                  LIBS=['sll_memory','sll_precision','sll_assertion','sll_constants'],
                  F90FLAGS =['-g', '-W', '-Wall', '-Wextra', '-pedantic', '-std=f2003', '-ffree-line-length-none', '-DGFORTRAN'])
#print "GFORTRAN is :", env['GFORTRAN']
#env.Replace(	
#		F90FLAGS = OPT+' -fpp',
#		FORTRANMODDIR = ZZZZZZ
#env.Append(LIBS = ['nsl', 'socket'])

env.Library('sll_memory',    ["../memory/sll_memory.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Library('sll_assertion', ["../assert/sll_assert.F90"])
env.Library('sll_constants', ["../constants/numeric_constants.F90"])
env.Program('unit_test', ["unit_test.F90", "sll_splines.F90"])



