# SCons file for the unit test of the spline module
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname() 

print 'Building the splines module...'
print 'hostname : ' + hostname
print 'platform : ' + platform

env = Environment( ENV=os.environ,
                   F90PATH= ['../memory','../precision','../assert', 
                             '../numerical_utilities','../constants'],
#                  FORTRANMODDIRPREFIX= '-fmod', 
                   LIBPATH= ['.'],
                   LIBS=['sll_constants','sll_memory','sll_precision',
                         'sll_assertion','sll_tridiagonal','sym_penta_diagonal'],
                   F90FLAGS =['-g', '-W', '-Wall', '-Wextra', '-pedantic', 
                              '-std=f2003', '-ffree-line-length-none', 
                              '-DGCC -lm'])
#print "GFORTRAN is :", env['GFORTRAN']
#env.Replace(	
#		F90FLAGS = OPT+' -fpp',
#		FORTRANMODDIR = ZZZZZZ
#env.Append(LIBS = ['nsl', 'socket'])

env.Library('sll_memory', ["../memory/sll_memory.F90"])
env.Library('sll_tridiagonal', ["../numerical_utilities/tridiagonal.F90"])
env.Library('sll_precision', ["../precision/sll_working_precision.F90"])
env.Library('sll_assertion', ["../assert/sll_assert.F90"])
env.Library('sll_constants', ["../constants/numeric_constants.F90"])
env.Program('unit_test', ["unit_test.F90", "sll_splines.F90", "test_func_module.F90",
 "test_processes_module.F90", "util_constants.F90"])
env.Program('unit_test_nonuniform', ["unit_test_nonuniform.F90", "cubic_nonuniform_splines.F90"])
env.Program('polar_SL', ["polar_SL.F90", "sll_splines.F90","cubic_nonuniform_splines.F90"])

env.Library('sym_penta_diagonal', ["../numerical_utilities/sym_penta_diagonal.c"])
env.Library('sym_penta_diagonal_h', ["../numerical_utilities/sym_penta_diagonal.h"])
env.Program('quintic_spline_tester', ["quintic_spline_tester.c", 
            'quintic_spline.c', 'quintic_spline.h'])

#env.Program('simu_spline', ["simu_spline.F90", "sll_splines.F90", "util_constants.F90"])
