#!/usr/bin/perl
# 
# filter for perf report
# 
# ======================================================================
# Written by Antoine Le Hyaric
# http://www.ljll.math.upmc.fr/lehyaric
# ======================================================================
# [[shell:header\alh 'perf_report']] (cf [[file:~/alh/bin/headeralh]])
# emacs-keywords brief="filter for perf report" default=0 perl start=10/04/2015 written

use strict;
use warnings;

# find latest data file to get its tag
my $latest=`ls -1t perf_*.data|head -1`;
$latest=~/perf_(.*)\.data$/ or die;
my $tag=$1;

# create report with same tag
open REPORT,"> report_$tag.txt" or die;

print REPORT "perf_report\n\n";

# [[man:perf-report]] applied on default perf.data
open PERF,"perf report --stdio|" or die;
my $count=0;
foreach(<PERF>){
  if($count++<40){print REPORT $_}
}
close PERF;
close REPORT;

# Local Variables:
# mode:cperl
# ispell-local-dictionary:"british"
# coding:utf-8
# eval:(flyspell-prog-mode)
# eval:(outline-minor-mode)
# End:
# LocalWords: emacs
