# Pastix lib requires linking to a blas library.
# It is up to the user of this module to find a BLAS and link to it.
# Pastix requires SCOTCH 


FIND_PATH(SCOTCH_INCLUDE_DIRS
		NAMES scotch.h scotchf.h 
		HINTS ${SCOTCH_ROOT}
		PATH_SUFFIXES include Include INCLUDE
		DOC "PATH TO scotch.h and scotchf.h")

FIND_LIBRARY(SCOTCH_LIBRARY
		NAMES scotch
		HINTS ${SCOTCH_ROOT}
		PATH_SUFFIXES lib Lib LIB
		DOC "PATH TO libscotch.a")

FIND_LIBRARY(SCOTCHERR_LIBRARY
		NAMES scotcherr
		HINTS ${SCOTCH_ROOT}
		PATH_SUFFIXES lib Lib LIB
		DOC "PATH TO libscotcherr.a")

FIND_LIBRARY(SCOTCHERREXIT_LIBRARY
		NAMES scotcherrexit
		HINTS ${SCOTCH_ROOT}
		PATH_SUFFIXES lib Lib LIB
		DOC "PATH TO libscotcherrexit.a")

SET (SCOTCH_LIBRARIES ${SCOTCH_LIBRARY};${SCOTCHERR_LIBRARY};${SCOTCHERREXIT_LIBRARY})
IF (SCOTCH_INCLUDE_DIRS AND SCOTCH_LIBRARIES)
  SET(SCOTCH_FOUND YES)
ENDIF(SCOTCH_INCLUDE_DIRS AND SCOTCH_LIBRARIES)
