find_path(FFTW_INCLUDE_DIRS
		NAMES fftw3.f03
		HINTS ${FFTW_ROOT}
		PATH_SUFFIXES include Include INCLUDE
		DOC "PATH TO fftw3.f03")
find_library(FFTW_LIBRARIES
		NAMES fftw3
		HINTS ${FFTW_ROOT}
		PATH_SUFFIXES lib Lib LIB
		DOC "PATH TO libfftw3.a")
if (FFTW_INCLUDE_DIRS AND FFTW_LIBRARIES)
  set(FFTW_FOUND YES)
endif(FFTW_INCLUDE_DIRS AND FFTW_LIBRARIES)
