IF(Fortran_COMPILER STREQUAL 'INTEL')
   SET(BLA_VENDOR "Intel")
ENDIF()

IF (APPLE)
   FIND_LIBRARY(LAPACK_LIBRARIES  lapack)
   FIND_LIBRARY(BLAS_LIBRARIES    blas)
ELSE()
   FIND_PACKAGE(LAPACK REQUIRED)
   FIND_PACKAGE(BLAS   REQUIRED)
ENDIF()


SET(LINK_LIBRARIES ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES})
