MODULE SPM_DEF
    IMPLICIT NONE 

    INTEGER, PARAMETER :: SPM_INTS_KIND=4
    INTEGER, PARAMETER :: SPM_INTL_KIND=8 ! TODO a remettre a 8
#ifdef _CUSP    
    INTEGER, PARAMETER :: SPM_COEF_KIND=4
#else
    INTEGER, PARAMETER :: SPM_COEF_KIND=8
#endif
    INTEGER, PARAMETER :: SPM_SUCCESS=1
    INTEGER, PARAMETER :: SPM_IPARM_VERBOSE=-1
    INTEGER, PARAMETER :: SPM_API_VERBOSE_NOT=-1 
    INTEGER, PARAMETER :: SPM_IPARM_MATRIX_VERIFICATION=-1
    INTEGER, PARAMETER :: SPM_API_YES=-1
    INTEGER, PARAMETER :: SPM_SOLVER_PASTIX=-1
    INTEGER, PARAMETER :: SPM_IPARAM_DOF=-1
    INTEGER, PARAMETER :: SPM_IPARAM_SYM=-1
    INTEGER, PARAMETER :: SPM_BOOLEAN_FALSE=-1
    INTEGER, PARAMETER :: SPM_IPARAM_BASEVAL=-1
    INTEGER, PARAMETER :: SPM_RPARAM_EPSILON_ERROR=-1
    INTEGER, PARAMETER :: SPM_ASSEMBLY_ADD=-1
    INTEGER, PARAMETER :: SPM_ASSEMBLY_FOOL=-1


    INTEGER, PARAMETER :: SPM_NULL_FMT                          = -1
    INTEGER, PARAMETER :: SPM_COO_FMT                           = 0
    INTEGER, PARAMETER :: SPM_CSC_FMT                           = 1 
    INTEGER, PARAMETER :: SPM_CSR_FMT                           = 2
    INTEGER, PARAMETER :: SPM_IJV_FMT                           = 3

    INTEGER, PARAMETER :: SPM_SOLVER_CUSP_CG                    = 0
    INTEGER, PARAMETER :: SPM_SOLVER_CUSP_GMRES                 = 1 
    INTEGER, PARAMETER :: SPM_SOLVER_CUSP_BICGSTAB              = 2
    INTEGER, PARAMETER :: SPM_SOLVER_CUSP_JACOBI                = 3 
    INTEGER, PARAMETER :: SPM_SOLVER_BASIC_CG                   = 4
    INTEGER, PARAMETER :: SPM_SOLVER_BASIC_GS                   = 5

    INTEGER, PARAMETER :: SPM_NIPARAM_SOLVER                    = 10
    INTEGER, PARAMETER :: SPM_IPARAM_SOLVER                     = 1 
    INTEGER, PARAMETER :: SPM_IPARAM_SOLVER_NITER               = 2 
    INTEGER, PARAMETER :: SPM_IPARAM_SOLVER_RESTART             = 3
    INTEGER, PARAMETER :: SPM_IPARAM_SOLVER_PRECOND             = 4 
    INTEGER, PARAMETER :: SPM_IPARAM_SOLVER_MAXITER             = 5 

    INTEGER, PARAMETER :: SPM_NRPARAM_SOLVER                    = 10
    INTEGER, PARAMETER :: SPM_RPARAM_SOLVER_RTOL                = 1
    INTEGER, PARAMETER :: SPM_RPARAM_SOLVER_OMEGA               = 2 
    INTEGER, PARAMETER :: SPM_RPARAM_SOLVER_RESNORM             = 3


    INTEGER, PARAMETER :: SPM_IJV_MAXSIZE                       = 1000

!CONTAINS
END MODULE SPM_DEF

