import os

warn_message = """
!!------------------------------------------------------------------------------
!! <auto-generated>
!!     This code was generated by a tool.
!!     Changes to this file may cause incorrect behavior and will be lost if
!!     the code is regenerated.
!! </auto-generated>
!!------------------------------------------------------------------------------
"""

def prepend_warn_message(root) :
 for directory, subdirs, names in os.walk(root):
  for name in names:
   if name[-8:] == "_pgi.F90":
    path = os.path.join(directory, name)
    with open(path,'r+') as f:
      text = f.read()
      f.seek(0) # rewind
      f.write(warn_message + text) # write the new line before

def recursive_replace(root, pattern, replace) :
 for directory, subdirs, names in os.walk(root):
  for name in names:
   if name[-8:] == "_pgi.F90":
    path = os.path.join(directory, name)
    text = open(path).read()
    if pattern in text:
     open(path,'w').write(text.replace(pattern,replace))


prepend_warn_message('.')
recursive_replace('.','#','!')
recursive_replace('.',';','\n')
