import os
import textwrap

warn_message = """
!!------------------------------------------------------------------------------
!! <auto-generated>
!!     This code was generated by a tool.
!!     Changes to this file may cause incorrect behavior and will be lost if
!!     the code is regenerated.
!! </auto-generated>
!!------------------------------------------------------------------------------
"""

def prepend_warn_message(root) :
 for directory, subdirs, names in os.walk(root):
  for name in names:
   if name[-8:] == "_pgi.F90":
    path = os.path.join(directory, name)
    with open(path,'r+') as f:
      text = f.read()
      f.seek(0) # rewind
      f.write(warn_message + text) # write the new line before

def recursive_replace(root, pattern, replace) :
 for directory, subdirs, names in os.walk(root):
  for name in names:
   if name[-8:] == "_pgi.F90":
    path = os.path.join(directory, name)
    text = open(path).read()
    if pattern in text:
     open(path,'w').write(text.replace(pattern,replace))

def insert_newlines(root, every):
 for directory, subdirs, names in os.walk(root):
  for name in names:
   if name[-8:] == "_pgi.F90":
    path = os.path.join(directory, name)
    text = '\n'
    for line in open(path):
      if( len(line) > every):
        text += ' & \n'.join(textwrap.wrap(line, 72))+'\n'
      else:
        text += line
    open(path,'w').write(text)


recursive_replace('.','#','!')
recursive_replace('.',';','\n')
insert_newlines('.', every=240)
prepend_warn_message('.')
