!Title: Subroutine Errout

!Subroutine: errout
!     Outputs an error message
!     PRTFIL - unit number for print-out
!     SEVRTY - 'W' - Warning 'F' - Fatal
!     WHERE  - in which program or subroutine
!     ErrMsg - error message
subroutine errout( prtfil, sevrty, where, ErrMsg )

 implicit none
 integer prtfil, Last
 character sevrty *1, where *(*), ErrMsg *(*)

 write( prtfil, * )

select case ( sevrty )  !     *** Severity ***
case ( 'W' )
   write(prtfil,"(/10x,a)") '*** WARNING ***'
case ( 'F' )
    write(prtfil,"(/10x,a)") '*** FATAL ERROR ***'
case default
     write(prtfil,"(/10x,a)") '*** FATAL ERROR ***'
     write(prtfil,"(/10x,a)") 'Error handler (ERROUT) called with unknown severity level: ', SEVRTY
end select

 Last = len( where )
 write( prtfil,"(/10x,a)") 'Generated by program or subroutine: ', where( 1:Last )

 Last = len( ErrMsg )
 write( prtfil,"(/10x,a)") ErrMsg(1:Last)
 write( prtfil,"(/10x,a)")

! return or stop depending on severity

if ( sevrty == 'W' ) then
 return
else
 stop 'Fatal Error: See print file for details'
end if

end subroutine errout

