# SCons file for timer module
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'Building the timer module...'
print 'hostname: ' + hostname
print 'platform: ' + platform

env = Environment( ENV = os.environ,
                   GCCFLAGS = ['-g', '-W', '-Wall', '-pedantic', '-ansi'],
                   F90FLAGS = ['-g', '-W', '-Wall', '-Wextra',
                   '-ffree-line-length-none', '-DGFORTRAN'],
                   LIBS = ['rt'])

env.Program('unit_test',['sll_timer_c.c', 'utils_functions.c', 'sll_timer_f.F90', 'unit_test.F90'] )
