# SCons file for timer module
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'Building the timer module...'
print 'hostname: ' + hostname
print 'platform: ' + platform

env = Environment( ENV = os.environ,
                   F90FLAGS = ['-g', '-W', '-Wall',
                   '-ffree-line-length-none', '-DGFORTRAN'])

env.Program('unit_test',['sll_timer.F90', 'unit_test.F90'] )
