
clear:
	find . -name '*.mod' -exec rm {} \;
	find . -name '*.a' -exec rm {} \;
	find . -name '*.o' -exec rm {} \;
	find . -name 'CMakeCache.txt' -exec rm {} \;
	find . -name 'CTestTestfile.cmake' -exec rm {} \;
	find . -name 'cmake_install.cmake' -exec rm {} \;

del_orig_files:
	find . -name '.orig' -exec rm {} \;
