SET(FFTW_INCLUDE_DIRS     "/softs/fftw/gcc47/3.3/include"     CACHE PATH " " FORCE)
SET(FFTW_LIBRARY          "/softs/fftw/gcc47/3.3/lib/libfftw3.a"    CACHE FILEPATH " " FORCE)
SET(HDF5_C_LIBRARY        "/softs/hdf5/gcc47/1.8.8/lib/libhdf5.a" CACHE FILEPATH " " FORCE)
SET(HDF5_FORTRAN_LIBRARY  "/softs/hdf5/gcc47/1.8.8/lib/libhdf5_fortran.a" CACHE FILEPATH " " FORCE)
SET(HDF5_INCLUDE_DIRS     "/softs/hdf5/gcc47/1.8.8/include" CACHE PATH " " FORCE)
SET(PASTIX_ROOT           "/softs/cemracs/pastix/gcc47" CACHE PATH " " FORCE)
SET(SCOTCH_ROOT           "/softs/cemracs/scotch/gcc47" CACHE PATH " " FORCE)
