set(SLL_COMP "${Fortran_COMPILER_NAME} ${Fortran_COMPILER_VERSION}")
if(CMAKE_BUILD_TYPE MATCHES "Debug")
  set(SLL_COMP "${SLL_COMP} (${CMAKE_Fortran_FLAGS_DEBUG})")
else()
  set(SLL_COMP "${SLL_COMP} (${CMAKE_Fortran_FLAGS_RELEASE})")
endif()
message(STATUS "SLL_COMP:${SLL_COMP}")
add_definitions(-DSLL_COMP="${SLL_COMP}")
