SET(CTEST_PROJECT_NAME "SeLaLib")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

SET(CTEST_DROP_SITE_CDASH TRUE)
IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "irma-webhpc")
  SET(CTEST_DROP_LOCATION "/CDash/submit.php?project=SeLaLib")
  #SET(CTEST_TRIGGER_SITE "")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
