FIND_PROGRAM(FORCHECK_EXECUTABLE
  NAMES forchk
  PATHS $ENV{FCKDIR}/bin /usr/bin /bin /usr/local/bin
  DOC "Performs a full static analysis of Fortran programs.")

IF (FORCHECK_EXECUTABLE)
  SET (FORCHECK_FOUND "YES")
ENDIF (FORCHECK_EXECUTABLE)

MARK_AS_ADVANCED(
  FORCHECK_FOUND
  FORCHECK_EXECUTABLE
  )

IF(FORCHECK_FOUND)

   FILE(GLOB_RECURSE SRCS_LIST *.F90)
   FOREACH(F90FILE ${SRCS_LIST}) 
      IF(DEFINED SRCS)
         SET(SRCS "${SRCS} ${F90FILE}")
      ELSE()
         SET(SRCS "${F90FILE}")
      ENDIF()
   ENDFOREACH(F90FILE) 

   GET_PROPERTY(INCS_DIRS DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/prototype/src PROPERTY INCLUDE_DIRECTORIES)

   FOREACH(DIR ${INCS_DIRS})
      IF(DEFINED INCS)
         SET(INCS "${INCS},${DIR}")
      ELSE()
         SET(INCS "${DIR}")
      ENDIF()
   ENDFOREACH()

   ADD_CUSTOM_TARGET(forcheck "${FORCHECK_EXECUTABLE} -define DEBUG,GFORTRAN -I ${INCS} -l mylistfile -ff ${SRCS} $(FCKDIR)/share/forcheck/MPI.flb"  COMMENT "Forcheck the source code" VERBATIM)

ENDIF(FORCHECK_FOUND)
