SET(CMAKE_CXX_COMPILER "icpc" )
SET(CMAKE_C_COMPILER   "icc")
SET(CMAKE_Fortran_COMPILER "ifort")
SET(FFTW_ENABLED "ON")
SET(FFTW_INCLUDE_DIRS "/opt/local/include")
SET(FFTW_LIBRARY "/opt/local/lib/libfftw3.a")
SET(FFT_LIB "FFTW")
SET(HDF5_C_LIBRARY "/opt/local/lib/libhdf5.a")
SET(HDF5_FORTRAN_LIBRARY "/opt/local/lib/libhdf5_fortran.a")
SET(HDF5_INCLUDE_DIRS "/opt/local/include")
SET(HDF5_PARALLEL_ENABLED "ON")
SET(MPI_Fortran_COMPILER "mpiifort")
