BLAS_atlas_LIBRARY:FILEPATH=/usr/lib/libatlas.so.3gf
BLAS_f77blas_LIBRARY:FILEPATH=/usr/lib/libf77blas.so.3gf
CMAKE_Fortran_COMPILER:FILEPATH=/usr/bin/gfortran
CMAKE_Fortran_FLAGS_DEBUG:STRING=-g -Wall -ffree-line-length-none -fall-intrinsics -fbounds-check -fbacktrace -ffpe-trap=zero,overflow,underflow -O0
CMAKE_Fortran_FLAGS_RELEASE:STRING=-w -ffree-line-length-none -fall-intrinsics -O3
FFTW_ENABLED:BOOL=ON
FFTW_INCLUDE_DIRS:PATH=/usr/include
FFTW_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3.so
FFTW_MPI_INCLUDE_DIR:PATH=/usr/include
FFTW_MPI_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3_mpi.so
FFTW_THREADS_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3_threads.so
FFT_DEFAULT_LIBRARY:STRING=SLLFFT
HDF5_C_LIBRARY:FILEPATH=/usr/lib/libhdf5.so
HDF5_ENABLED:BOOL=ON
HDF5_FORTRAN_LIBRARY:FILEPATH=/usr/lib/libhdf5_fortran.so
HDF5_INCLUDE_DIRS:PATH=/usr/include
HDF5_PARALLEL_ENABLED:BOOL=ON
LAPACK_lapack_LIBRARY:FILEPATH=/usr/lib/liblapack.so
MPI_Fortran_COMPILER:FILEPATH=/usr/bin/mpif90
MPI_Fortran_INCLUDE_PATH:STRING=/usr/lib/openmpi/include;/usr/lib/openmpi/lib
MPI_Fortran_LIBRARIES:STRING=/usr/lib/openmpi/lib/libmpi_f90.so;/usr/lib/openmpi/lib/libmpi_f77.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libopen-rte.so;/usr/lib/openmpi/lib/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libnsl.so;/usr/lib/x86_64-linux-gnu/libutil.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so
MPI_MODULE_ENABLED:BOOL=ON
