# Scons file for the unit test of the integrators
import os
import socket
import distutils.util

platform = distutils.util.get_platform()
hostname = socket.gethostname()

print 'hostname: ' + hostname
print 'platform: ' + platform
# WATCH OUT FOR GFORTRAN VARIABLE
env = Environment( F90PATH = ['../precision','../constants'],
                   FORTRANMODDIRPREFIX= '-J',
                   LIBPATH= ['.'],
                   LIBS= ['sll_precision','sll_constants'],
                   F90FLAGS= ['-g','-W', '-Wall', '-Wextra', '-pedantic', '-std=f2003', '-ffree-line-length-none', '-DGFORTRAN'])

env.Library('sll_precision',["../precision/sll_working_precision.F90"])
env.Library('sll_constants',["../constants/numeric_constants.F90"])
env.Program('unit_test', ["unit_test.F90","test_func_module.F90","gauss_legendre.F90"])
